### PR TITLE
ISSUE-222 - zoo.cfg updated parameters are not picked up during rolli…

### LINKED ISSUE #222: zoo.cfg updated parameters are not picked up during rolling restarts
### Description

Updating ZK parameters like `initLimit`, `tickTime` are not reflected in ZK when the cluster is restarted. 
Steps to reproduce:
- deploy a new ZK cluster 
- update `initLimit` in ZK spec
- rolling restart is triggered and one would expect the new value to be reflected in zk runtime
This is not happing and `/data/conf/zoo.cfg` configuration file used in zk command line does not reflect the change.

https://github.com/adobe/zookeeper-operator/blob/dede2bacf9ff56fa85bd81286cea0fd20815e632/pkg/zk/generators.go#L203-L217

#### Analysis

Following the param change it seems the `/conf/zoo.cfg` correctly picks up the change but the actual `/data/conf/zoo.cfg` is only copied once during initial installation (and never updated)
https://github.com/adobe/zookeeper-operator/blob/master/docker/bin/zookeeperStart.sh#L140-L143

### Importance
must-have

### Suggestions for an improvement

_(How do you suggest to fix or proceed with this issue?)_

### PR DESCRIPTION
**Pull request by amuraru**
Force refresh of /data/conf/zoo.cfg content on zk pod restart

Fixes https://github.com/pravega/zookeeper-operator/issues/222

### CODE REVIEW

**Comment by amuraru** [comment]
@alungu @azun @dobrerazvan @alexander-falca please review
I started a PR internally here to expedite the fix and plan to do a similar PR upstream

**Review by alexander-falca — APPROVED** [review]
:+1:

**Review by ecojan — APPROVED** [review]

**Review by dobrerazvan — APPROVED** [review]

File: docker/bin/zookeeperStart.sh [hunk 1]
```diff
@@ -138,13 +138,18 @@ fi
...
 fi
+echo Copying /conf contents to writable directory, to support Zookeeper dynamic reconfiguration
+cp -f /conf/log4j.properties $ZOOCFGDIR
+cp -f /conf/log4j-quiet.properties $ZOOCFGDIR
+cp -f /conf/env.sh $ZOOCFGDIR
+# create or refresh $ZOOCFGDIR/zoo.cfg appending to /conf/zoo.cfg
+# the last dynamicConfigFile entry (if available)
+cat \
+<<<$(cat /conf/zoo.cfg) \
+<<<$(grep 'dynamicConfigFile=' $ZOOCFGDIR/zoo.cfg 2>/dev/null) \
```
Comment (alungu) [inline docker/bin/zookeeperStart.sh]: If we already have the `dynamicConfigFile` property (which will happen in most of the cases), wouldn't this result in a file with both the new and the old `dynamicConfigFile` property? Because we are writing the full content of `/conf/zoo.cfg` + another `dynamicConfigFile`. I think we should use `sed` or something similar to replace the old `dynamicConfigFile`

Comment (amuraru) [reply docker/bin/zookeeperStart.sh]: updated to cover for this

**Review by alungu — APPROVED** [review]
